name: Test Coverage

##
## Run cobertura task and publish test coverage report to coverall.io
##

on:
    # Trigger the workflow on push or pull request,
    # but only for the master and develop branches
    push:
        branches:
            - dont_run
#            - master
#            - develop  ## disable coverage on develop branch until cobertura supports Gradle 7: https://github.com/stevesaliman/gradle-cobertura-plugin/pull/178

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Java
              uses: actions/setup-java@v3
              with:
                  distribution: zulu
                  java-version: 11

            - name: Cobertura coveralls.io
              run: ./gradlew cobertura coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
