name: Java CI

##
## Run cobertura task and publish test coverage report to coverall.io
##

on:
    # Trigger the workflow on push or pull request,
    # but only for the master and develop branches
    push:
        branches:
            - master
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        name: Test Coverage

        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: '1.8'

            - name: Cobertura coveralls.io
              run: ./gradlew cobertura coveralls
